{application,rummage_ecto,
             [{applications,[kernel,stdlib,elixir,logger,ecto]},
              {description,"A library that allows searching, sorting and paginating ecto queries\n"},
              {modules,['Elixir.Rummage.Ecto','Elixir.Rummage.Ecto.Config',
                        'Elixir.Rummage.Ecto.CustomHook.KeysetPaginate',
                        'Elixir.Rummage.Ecto.CustomHook.SimpleSearch',
                        'Elixir.Rummage.Ecto.CustomHook.SimpleSort',
                        'Elixir.Rummage.Ecto.Hook',
                        'Elixir.Rummage.Ecto.Hook.CustomPaginate',
                        'Elixir.Rummage.Ecto.Hook.CustomSearch',
                        'Elixir.Rummage.Ecto.Hook.CustomSort',
                        'Elixir.Rummage.Ecto.Hook.Paginate',
                        'Elixir.Rummage.Ecto.Hook.Search',
                        'Elixir.Rummage.Ecto.Hook.Sort',
                        'Elixir.Rummage.Ecto.Schema',
                        'Elixir.Rummage.Ecto.Services.BuildSearchQuery']},
              {registered,[]},
              {vsn,"2.0.0-rc.0"}]}.
