{application,as_nested_set,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"An ecto based Nested set model implementation\n"},
              {modules,['Elixir.AsNestedSet','Elixir.AsNestedSet.Helper',
                        'Elixir.AsNestedSet.Model',
                        'Elixir.AsNestedSet.Modifiable',
                        'Elixir.AsNestedSet.Queriable',
                        'Elixir.AsNestedSet.Scoped',
                        'Elixir.AsNestedSet.Traversable']},
              {registered,[]},
              {vsn,"3.1.1"}]}.
