{application,aruspex,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"A configurable constraint solver with an API based on JSR 331.\n"},
              {modules,['Elixir.Aruspex','Elixir.Aruspex.Constraint',
                        'Elixir.Aruspex.Evaluation','Elixir.Aruspex.Logger',
                        'Elixir.Aruspex.Problem','Elixir.Aruspex.Strategy',
                        'Elixir.Aruspex.Strategy.Ac3',
                        'Elixir.Aruspex.Strategy.Dfs',
                        'Elixir.Aruspex.Strategy.SimulatedAnnealing',
                        'Elixir.Enumerable.Aruspex.Strategy.Ac3',
                        'Elixir.Enumerable.Aruspex.Strategy.Dfs',
                        'Elixir.Enumerable.Aruspex.Strategy.SimulatedAnnealing']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
