{application,ecto_identifier,
             [{applications,[kernel,stdlib,elixir,logger,git_hooks,nanoid,
                             ecto]},
              {description,"Provides some custom Ecto types to manage autogenerated unique identifiers."},
              {modules,['Elixir.Ecto.Nanoid']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
